version: '2'
services:
    rts-app:
        image: rts
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://rts-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=rts
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rts-mongodb:
        extends:
            file: mongodb.yml
            service: rts-mongodb
