@startuml
class DocumentService << (S,#FF7700) Singleton >> {
+DocumentRTS data
-onChangeTitle()
-onUpdateDocument()
}




class DocumentRTS << (D,orchid) >> {
String id
String title
Author author
Set<Content> content
ContentType type
byte[] thump
String thumpContentType
}
@enduml
